AWSTemplateFormatVersion: '2010-09-09'
Description: 'VPC setup testing'
Parameters:
  VpcCIDR:
    Description: This CIDR notation is used to create the VPC.
    Type: String
    Default: 10.192.0.0/16
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
Outputs:
  VPC:
    Description: A reference to the created VPC.
    Value: !Ref VPC


  LambdaS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${EnvironmentName}.lambda.userverify'
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: StorageRules
            Prefix: standardIA
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
      VersioningConfiguration:
        Status: Suspended
  LoadBalancerHttpsCertificate:
    Type: AWS::ElasticLoadBalancingV2::ListenerCertificate
    Properties: 
      Certificates: 
        - arn:aws:iam::757570737110:server-certificate/sslProd
      ListenerArn: !GetAtt PublicLoadBalancerListener.Arn
    DependsOn: PublicLoadBalancerListener

          - Sid: Enabling EC2 Autoscaling 
            Effect: Allow
            Principal: 
              AWS: 'arn:aws:iam::${AccountId}:role/aws-service-role/autoscaling.amazonaws.com/AWSServiceRoleForAutoScaling'
            Action: 'kms:*'
            Resource: '*'


      - PolicyName: KmsKeyEBS
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - 'kms:DescribeKey'
                - 'kms:GenerateDataKey*'
                - 'kms:Decrypt'
                - 'kms:Encrypt'
                - 'kms:ReEncrypt*'
              Resource: 
              - !GetAtt EBSkey.Arn